name: Deploy to Render

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Trigger Render Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
